# Generated by Django 2.2.10 on 2020-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=10, null=True)),
                ('fecha_compra', models.DateField(auto_now=True, verbose_name='Fecha de compra')),
            ],
        ),
    ]
