# Generated by Django 2.2.10 on 2020-03-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_auto_20200302_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='nombre',
            new_name='idPro',
        ),
    ]
