# Generated by Django 2.2.10 on 2020-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20200303_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='idUser',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
